<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Sceanrio1</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-07-25T11:21:26</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>6a3f0447-0464-4c4d-868d-9232ca4ee78e</testSuiteGuid>
   <testCaseLink>
      <guid>2cbe2636-7c63-426c-a627-10ea8fdeb939</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Day 2 Training/Training/Scenario1-Variables</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d1c994b-5a82-4b4b-884f-169511eb4aa8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d62cb1ca-b672-4568-8d97-f524980ab0b1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e11f033c-b4d6-4247-a5b5-76fa565dbf2b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
