<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LeaveDetails</name>
   <tag></tag>
   <elementGuidId>afe7bbdd-b381-4a74-9044-098061881961</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;dashboard-quick-launch-panel-menu_holder&quot;]/table/tbody/tr/td[2]/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/webres_5acde3dbd3adc6.90334155/orangehrmLeavePlugin/images/MyLeave.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;dashboard-quick-launch-panel-menu_holder&quot;]/table/tbody/tr/td[2]/div/a/img</value>
   </webElementProperties>
</WebElementEntity>
